import Head from "next/head";
import Image from "next/image";
import Cta from "../components/Cta";
import Footer from "../components/Footer/Footer";
import Hero from "../components/Hero";
import LuuY from "../components/LuuY";
import MoreInfoModal from "../components/MoreInfoModal";
import MoreInfo from "../components/MoreInfoModal";
import Navbar from "../components/Navbar/Navbar";
import Sanphamkhac from "../components/Sanphamkhac";
import Teacher from "../components/Teachers";
import Uudiem from "../components/Uudiem";
import UpdateInformation from "../components/UpdateInfo/UpdateInformation";

export default function Home() {
  return (
    <div>
      <Navbar />
      <Head>
        <title>Ed -Circle Education Website</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <LuuY />
      <Uudiem />
      <Teacher />
      <Sanphamkhac />
      <MoreInfoModal />
      <UpdateInformation />
      <Cta />
      <Footer />
    </div>
  );
}
